//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.2.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
// @ts-nocheck

export class AuthApiBase {
  authToken = "";
  protected constructor() {}

  // Enforce always return empty string as baseUrl
  getBaseUrl(defaultUrl: string, baseUrl: string) {
    return "";
  }

  setAuthToken(token: string) {
    this.authToken = token;
  }

  protected transformOptions(options: any): Promise<any> {
    if (this.authToken) {
      options.headers["authorization"] = `Bearer ${this.authToken}`;
    }
    return Promise.resolve(options);
  }
}

export class AiHelperCommonClient extends AuthApiBase {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        super();
        this.http = http ? http : window as any;
        this.baseUrl = this.getBaseUrl("", baseUrl);
    }

    /**
     * @return OK
     */
    getSettings(): Promise<AiHelperSettings> {
        let url_ = this.baseUrl + "/api/aihelper/settings";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.http.fetch(url_, transformedOptions_);
        }).then((_response: Response) => {
            return this.processGetSettings(_response);
        });
    }

    protected processGetSettings(response: Response): Promise<AiHelperSettings> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = AiHelperSettings.fromJS(resultData200);
            return result200;
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AiHelperSettings>(null as any);
    }
}

export class AiHelperClient extends AuthApiBase {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        super();
        this.http = http ? http : window as any;
        this.baseUrl = this.getBaseUrl("", baseUrl);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    translate(body?: TranstlateCommand | undefined): Promise<AiRequestResult> {
        let url_ = this.baseUrl + "/api/aihelper/translate";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json-patch+json",
                "Accept": "application/json"
            }
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.http.fetch(url_, transformedOptions_);
        }).then((_response: Response) => {
            return this.processTranslate(_response);
        });
    }

    protected processTranslate(response: Response): Promise<AiRequestResult> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = AiRequestResult.fromJS(resultData200);
            return result200;
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AiRequestResult>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    generateDescription(body?: GenerateDescriptionCommand | undefined): Promise<AiRequestResult> {
        let url_ = this.baseUrl + "/api/aihelper/generate/description";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json-patch+json",
                "Accept": "application/json"
            }
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.http.fetch(url_, transformedOptions_);
        }).then((_response: Response) => {
            return this.processGenerateDescription(_response);
        });
    }

    protected processGenerateDescription(response: Response): Promise<AiRequestResult> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = AiRequestResult.fromJS(resultData200);
            return result200;
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AiRequestResult>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    generateProductImage(body?: GenerateProductImageCommand | undefined): Promise<AiRequestResult> {
        let url_ = this.baseUrl + "/api/aihelper/generate/productimage";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json-patch+json",
                "Accept": "application/json"
            }
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.http.fetch(url_, transformedOptions_);
        }).then((_response: Response) => {
            return this.processGenerateProductImage(_response);
        });
    }

    protected processGenerateProductImage(response: Response): Promise<AiRequestResult> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = AiRequestResult.fromJS(resultData200);
            return result200;
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AiRequestResult>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    generateProperties(body?: GeneratePropertiesCommand | undefined): Promise<AiRequestResult> {
        let url_ = this.baseUrl + "/api/aihelper/generate/properties";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json-patch+json",
                "Accept": "application/json"
            }
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.http.fetch(url_, transformedOptions_);
        }).then((_response: Response) => {
            return this.processGenerateProperties(_response);
        });
    }

    protected processGenerateProperties(response: Response): Promise<AiRequestResult> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = AiRequestResult.fromJS(resultData200);
            return result200;
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AiRequestResult>(null as any);
    }
}

export class AiHelperLogClient extends AuthApiBase {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        super();
        this.http = http ? http : window as any;
        this.baseUrl = this.getBaseUrl("", baseUrl);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    searchLog(body?: SearchAiRequestLogQuery | undefined): Promise<AiRequestLogSearchResult> {
        let url_ = this.baseUrl + "/api/aihelper/log/search";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json-patch+json",
                "Accept": "application/json"
            }
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.http.fetch(url_, transformedOptions_);
        }).then((_response: Response) => {
            return this.processSearchLog(_response);
        });
    }

    protected processSearchLog(response: Response): Promise<AiRequestLogSearchResult> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = AiRequestLogSearchResult.fromJS(resultData200);
            return result200;
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AiRequestLogSearchResult>(null as any);
    }

    /**
     * @param logLevel (optional) 
     * @return OK
     */
    getAiRequestLogById(logId: string, logLevel?: string | undefined): Promise<AiRequestLog> {
        let url_ = this.baseUrl + "/api/aihelper/log/{logId}?";
        if (logId === undefined || logId === null)
            throw new globalThis.Error("The parameter 'logId' must be defined.");
        url_ = url_.replace("{logId}", encodeURIComponent("" + logId));
        if (logLevel === null)
            throw new globalThis.Error("The parameter 'logLevel' cannot be null.");
        else if (logLevel !== undefined)
            url_ += "logLevel=" + encodeURIComponent("" + logLevel) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.http.fetch(url_, transformedOptions_);
        }).then((_response: Response) => {
            return this.processGetAiRequestLogById(_response);
        });
    }

    protected processGetAiRequestLogById(response: Response): Promise<AiRequestLog> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = AiRequestLog.fromJS(resultData200);
            return result200;
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AiRequestLog>(null as any);
    }
}

export class AiHelperSettings implements IAiHelperSettings {
    isEnabled?: boolean;
    logLevel?: string | undefined;

    constructor(data?: IAiHelperSettings) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.isEnabled = _data["isEnabled"];
            this.logLevel = _data["logLevel"];
        }
    }

    static fromJS(data: any): AiHelperSettings {
        data = typeof data === 'object' ? data : {};
        let result = new AiHelperSettings();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["isEnabled"] = this.isEnabled;
        data["logLevel"] = this.logLevel;
        return data;
    }
}

export interface IAiHelperSettings {
    isEnabled?: boolean;
    logLevel?: string | undefined;
}

export class AiProductContract implements IAiProductContract {
    name?: string | undefined;
    category?: string | undefined;
    description?: string | undefined;
    images?: string[] | undefined;

    constructor(data?: IAiProductContract) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.category = _data["category"];
            this.description = _data["description"];
            if (Array.isArray(_data["images"])) {
                this.images = [] as any;
                for (let item of _data["images"])
                    this.images!.push(item);
            }
        }
    }

    static fromJS(data: any): AiProductContract {
        data = typeof data === 'object' ? data : {};
        let result = new AiProductContract();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["category"] = this.category;
        data["description"] = this.description;
        if (Array.isArray(this.images)) {
            data["images"] = [];
            for (let item of this.images)
                data["images"].push(item);
        }
        return data;
    }
}

export interface IAiProductContract {
    name?: string | undefined;
    category?: string | undefined;
    description?: string | undefined;
    images?: string[] | undefined;
}

export class AiRequestLog implements IAiRequestLog {
    providerName?: string | undefined;
    model?: string | undefined;
    requestType?: string | undefined;
    taskType?: string | undefined;
    userId?: string | undefined;
    entityId?: string | undefined;
    requestDuration?: number;
    isSuccess?: boolean;
    requestContext?: string | undefined;
    prompt?: string | undefined;
    response?: string | undefined;
    errorText?: string | undefined;
    createdDate?: Date;
    modifiedDate?: Date | undefined;
    createdBy?: string | undefined;
    modifiedBy?: string | undefined;
    id?: string | undefined;

    constructor(data?: IAiRequestLog) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.providerName = _data["providerName"];
            this.model = _data["model"];
            this.requestType = _data["requestType"];
            this.taskType = _data["taskType"];
            this.userId = _data["userId"];
            this.entityId = _data["entityId"];
            this.requestDuration = _data["requestDuration"];
            this.isSuccess = _data["isSuccess"];
            this.requestContext = _data["requestContext"];
            this.prompt = _data["prompt"];
            this.response = _data["response"];
            this.errorText = _data["errorText"];
            this.createdDate = _data["createdDate"] ? new Date(_data["createdDate"].toString()) : undefined as any;
            this.modifiedDate = _data["modifiedDate"] ? new Date(_data["modifiedDate"].toString()) : undefined as any;
            this.createdBy = _data["createdBy"];
            this.modifiedBy = _data["modifiedBy"];
            this.id = _data["id"];
        }
    }

    static fromJS(data: any): AiRequestLog {
        data = typeof data === 'object' ? data : {};
        let result = new AiRequestLog();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["providerName"] = this.providerName;
        data["model"] = this.model;
        data["requestType"] = this.requestType;
        data["taskType"] = this.taskType;
        data["userId"] = this.userId;
        data["entityId"] = this.entityId;
        data["requestDuration"] = this.requestDuration;
        data["isSuccess"] = this.isSuccess;
        data["requestContext"] = this.requestContext;
        data["prompt"] = this.prompt;
        data["response"] = this.response;
        data["errorText"] = this.errorText;
        data["createdDate"] = this.createdDate ? this.createdDate.toISOString() : undefined as any;
        data["modifiedDate"] = this.modifiedDate ? this.modifiedDate.toISOString() : undefined as any;
        data["createdBy"] = this.createdBy;
        data["modifiedBy"] = this.modifiedBy;
        data["id"] = this.id;
        return data;
    }
}

export interface IAiRequestLog {
    providerName?: string | undefined;
    model?: string | undefined;
    requestType?: string | undefined;
    taskType?: string | undefined;
    userId?: string | undefined;
    entityId?: string | undefined;
    requestDuration?: number;
    isSuccess?: boolean;
    requestContext?: string | undefined;
    prompt?: string | undefined;
    response?: string | undefined;
    errorText?: string | undefined;
    createdDate?: Date;
    modifiedDate?: Date | undefined;
    createdBy?: string | undefined;
    modifiedBy?: string | undefined;
    id?: string | undefined;
}

export class AiRequestLogSearchResult implements IAiRequestLogSearchResult {
    totalCount?: number;
    results?: AiRequestLog[] | undefined;

    constructor(data?: IAiRequestLogSearchResult) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.totalCount = _data["totalCount"];
            if (Array.isArray(_data["results"])) {
                this.results = [] as any;
                for (let item of _data["results"])
                    this.results!.push(AiRequestLog.fromJS(item));
            }
        }
    }

    static fromJS(data: any): AiRequestLogSearchResult {
        data = typeof data === 'object' ? data : {};
        let result = new AiRequestLogSearchResult();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["totalCount"] = this.totalCount;
        if (Array.isArray(this.results)) {
            data["results"] = [];
            for (let item of this.results)
                data["results"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IAiRequestLogSearchResult {
    totalCount?: number;
    results?: AiRequestLog[] | undefined;
}

export class AiRequestResult implements IAiRequestResult {
    isSuccess?: boolean;
    result?: any | undefined;
    errorMessage?: string | undefined;

    constructor(data?: IAiRequestResult) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.isSuccess = _data["isSuccess"];
            this.result = _data["result"];
            this.errorMessage = _data["errorMessage"];
        }
    }

    static fromJS(data: any): AiRequestResult {
        data = typeof data === 'object' ? data : {};
        let result = new AiRequestResult();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["isSuccess"] = this.isSuccess;
        data["result"] = this.result;
        data["errorMessage"] = this.errorMessage;
        return data;
    }
}

export interface IAiRequestResult {
    isSuccess?: boolean;
    result?: any | undefined;
    errorMessage?: string | undefined;
}

export class GenerateDescriptionCommand implements IGenerateDescriptionCommand {
    product?: AiProductContract | undefined;
    targetLanguage?: string | undefined;
    userId?: string | undefined;
    entityId?: string | undefined;

    constructor(data?: IGenerateDescriptionCommand) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.product = _data["product"] ? AiProductContract.fromJS(_data["product"]) : undefined as any;
            this.targetLanguage = _data["targetLanguage"];
            this.userId = _data["userId"];
            this.entityId = _data["entityId"];
        }
    }

    static fromJS(data: any): GenerateDescriptionCommand {
        data = typeof data === 'object' ? data : {};
        let result = new GenerateDescriptionCommand();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["product"] = this.product ? this.product.toJSON() : undefined as any;
        data["targetLanguage"] = this.targetLanguage;
        data["userId"] = this.userId;
        data["entityId"] = this.entityId;
        return data;
    }
}

export interface IGenerateDescriptionCommand {
    product?: AiProductContract | undefined;
    targetLanguage?: string | undefined;
    userId?: string | undefined;
    entityId?: string | undefined;
}

export class GenerateProductImageCommand implements IGenerateProductImageCommand {
    product?: AiProductContract | undefined;
    userId?: string | undefined;
    entityId?: string | undefined;

    constructor(data?: IGenerateProductImageCommand) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.product = _data["product"] ? AiProductContract.fromJS(_data["product"]) : undefined as any;
            this.userId = _data["userId"];
            this.entityId = _data["entityId"];
        }
    }

    static fromJS(data: any): GenerateProductImageCommand {
        data = typeof data === 'object' ? data : {};
        let result = new GenerateProductImageCommand();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["product"] = this.product ? this.product.toJSON() : undefined as any;
        data["userId"] = this.userId;
        data["entityId"] = this.entityId;
        return data;
    }
}

export interface IGenerateProductImageCommand {
    product?: AiProductContract | undefined;
    userId?: string | undefined;
    entityId?: string | undefined;
}

export class GeneratePropertiesCommand implements IGeneratePropertiesCommand {
    product?: AiProductContract | undefined;
    jsonTemplate?: string | undefined;
    userId?: string | undefined;
    entityId?: string | undefined;

    constructor(data?: IGeneratePropertiesCommand) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.product = _data["product"] ? AiProductContract.fromJS(_data["product"]) : undefined as any;
            this.jsonTemplate = _data["jsonTemplate"];
            this.userId = _data["userId"];
            this.entityId = _data["entityId"];
        }
    }

    static fromJS(data: any): GeneratePropertiesCommand {
        data = typeof data === 'object' ? data : {};
        let result = new GeneratePropertiesCommand();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["product"] = this.product ? this.product.toJSON() : undefined as any;
        data["jsonTemplate"] = this.jsonTemplate;
        data["userId"] = this.userId;
        data["entityId"] = this.entityId;
        return data;
    }
}

export interface IGeneratePropertiesCommand {
    product?: AiProductContract | undefined;
    jsonTemplate?: string | undefined;
    userId?: string | undefined;
    entityId?: string | undefined;
}

export class SearchAiRequestLogQuery implements ISearchAiRequestLogQuery {
    providerName?: string | undefined;
    requestType?: string | undefined;
    taskType?: string | undefined;
    isSuccess?: boolean | undefined;
    userId?: string | undefined;
    entityId?: string | undefined;
    responseGroup?: string | undefined;
    objectType?: string | undefined;
    objectTypes?: string[] | undefined;
    objectIds?: string[] | undefined;
    keyword?: string | undefined;
    searchPhrase?: string | undefined;
    languageCode?: string | undefined;
    sort?: string | undefined;
    readonly sortInfos?: SortInfo[] | undefined;
    skip?: number;
    take?: number;

    constructor(data?: ISearchAiRequestLogQuery) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.providerName = _data["providerName"];
            this.requestType = _data["requestType"];
            this.taskType = _data["taskType"];
            this.isSuccess = _data["isSuccess"];
            this.userId = _data["userId"];
            this.entityId = _data["entityId"];
            this.responseGroup = _data["responseGroup"];
            this.objectType = _data["objectType"];
            if (Array.isArray(_data["objectTypes"])) {
                this.objectTypes = [] as any;
                for (let item of _data["objectTypes"])
                    this.objectTypes!.push(item);
            }
            if (Array.isArray(_data["objectIds"])) {
                this.objectIds = [] as any;
                for (let item of _data["objectIds"])
                    this.objectIds!.push(item);
            }
            this.keyword = _data["keyword"];
            this.searchPhrase = _data["searchPhrase"];
            this.languageCode = _data["languageCode"];
            this.sort = _data["sort"];
            if (Array.isArray(_data["sortInfos"])) {
                (this as any).sortInfos = [] as any;
                for (let item of _data["sortInfos"])
                    (this as any).sortInfos!.push(SortInfo.fromJS(item));
            }
            this.skip = _data["skip"];
            this.take = _data["take"];
        }
    }

    static fromJS(data: any): SearchAiRequestLogQuery {
        data = typeof data === 'object' ? data : {};
        let result = new SearchAiRequestLogQuery();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["providerName"] = this.providerName;
        data["requestType"] = this.requestType;
        data["taskType"] = this.taskType;
        data["isSuccess"] = this.isSuccess;
        data["userId"] = this.userId;
        data["entityId"] = this.entityId;
        data["responseGroup"] = this.responseGroup;
        data["objectType"] = this.objectType;
        if (Array.isArray(this.objectTypes)) {
            data["objectTypes"] = [];
            for (let item of this.objectTypes)
                data["objectTypes"].push(item);
        }
        if (Array.isArray(this.objectIds)) {
            data["objectIds"] = [];
            for (let item of this.objectIds)
                data["objectIds"].push(item);
        }
        data["keyword"] = this.keyword;
        data["searchPhrase"] = this.searchPhrase;
        data["languageCode"] = this.languageCode;
        data["sort"] = this.sort;
        if (Array.isArray(this.sortInfos)) {
            data["sortInfos"] = [];
            for (let item of this.sortInfos)
                data["sortInfos"].push(item ? item.toJSON() : undefined as any);
        }
        data["skip"] = this.skip;
        data["take"] = this.take;
        return data;
    }
}

export interface ISearchAiRequestLogQuery {
    providerName?: string | undefined;
    requestType?: string | undefined;
    taskType?: string | undefined;
    isSuccess?: boolean | undefined;
    userId?: string | undefined;
    entityId?: string | undefined;
    responseGroup?: string | undefined;
    objectType?: string | undefined;
    objectTypes?: string[] | undefined;
    objectIds?: string[] | undefined;
    keyword?: string | undefined;
    searchPhrase?: string | undefined;
    languageCode?: string | undefined;
    sort?: string | undefined;
    sortInfos?: SortInfo[] | undefined;
    skip?: number;
    take?: number;
}

export enum SortDirection {
    Ascending = "Ascending",
    Descending = "Descending",
}

export class SortInfo implements ISortInfo {
    sortColumn?: string | undefined;
    sortDirection?: SortInfoSortDirection;

    constructor(data?: ISortInfo) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.sortColumn = _data["sortColumn"];
            this.sortDirection = _data["sortDirection"];
        }
    }

    static fromJS(data: any): SortInfo {
        data = typeof data === 'object' ? data : {};
        let result = new SortInfo();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["sortColumn"] = this.sortColumn;
        data["sortDirection"] = this.sortDirection;
        return data;
    }
}

export interface ISortInfo {
    sortColumn?: string | undefined;
    sortDirection?: SortInfoSortDirection;
}

export class TranstlateCommand implements ITranstlateCommand {
    text?: string | undefined;
    targetLanguage?: string | undefined;
    userId?: string | undefined;
    entityId?: string | undefined;

    constructor(data?: ITranstlateCommand) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.text = _data["text"];
            this.targetLanguage = _data["targetLanguage"];
            this.userId = _data["userId"];
            this.entityId = _data["entityId"];
        }
    }

    static fromJS(data: any): TranstlateCommand {
        data = typeof data === 'object' ? data : {};
        let result = new TranstlateCommand();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["text"] = this.text;
        data["targetLanguage"] = this.targetLanguage;
        data["userId"] = this.userId;
        data["entityId"] = this.entityId;
        return data;
    }
}

export interface ITranstlateCommand {
    text?: string | undefined;
    targetLanguage?: string | undefined;
    userId?: string | undefined;
    entityId?: string | undefined;
}

export enum SortInfoSortDirection {
    Ascending = "Ascending",
    Descending = "Descending",
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}

/* eslint-disable */